version: '3'
services:
    frontend:
        build: ./client
        ports:
            - "${REACT_SERVER_PORT}:${REACT_SERVER_PORT}"
        volumes: 
            # using a volume rather than copying to allow live reloading in the container
            - ./client:/usr/src/app 
        tty: true
        environment: 
            - PORT=${REACT_SERVER_PORT}
            - REACT_APP_GO_SERVER_EXTERNAL_URL=${GO_SERVER_URL}
    backend:
        build: ./server
        depends_on: 
            -  mongo
        ports:
            - "80:8080"
        environment:
            - SPOTIFY_ID=${SPOTIFY_ID}
            - SPOTIFY_SECRET=${SPOTIFY_SECRET}
            - MUSIXMATCH_API_KEY=${MUSIXMATCH_API_KEY}
            - GO_SERVER_EXTERNAL_URL=${GO_SERVER_URL}
            - FRONTEND_SERVER_EXTERNAL_URL=${REACT_SERVER_URL}:${REACT_SERVER_PORT}
            - MONGO_CONNECTION_STRING=${MONGO_CONNECTION_STRING}
    mongo:
        image: mongo:4.2.6
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: password